dist: trusty
sudo: required
language: cpp
os:
  - linux
language: cpp
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=5 LLVM_VERSION=4.0
  - GCC_VERSION=6 LLVM_VERSION=4.0
  - GCC_VERSION=6 LLVM_VERSION=3.8
  - GCC_VERSION=6 LLVM_VERSION=3.9
  - GCC_VERSION=6 LLVM_VERSION=5.0
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=5 LLVM_VERSION=4.0
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=3.8
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=3.9
    - compiler: gcc
      env: GCC_VERSION=6 LLVM_VERSION=5.0
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise-3.9
      - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-4.9
      - g++-5
      - g++-6
      - clang-3.8
      - clang-3.9
      - clang-4.0
      - clang-5.0
      - libboost1.55
      - libboost1.55-dev
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libopenblas-dev
      - cmake
      - cmake-data
before_install:
  - ./bin/travisci_before_$TRAVIS_OS_NAME.sh
script:
  - ./bin/travisci_build_$TRAVIS_OS_NAME.sh
after_failure:
  - cat build/CMakeFiles/CMakeOutput.log
  - cat build/CMakeFiles/CMakeError.log
  - cat build_cblas/CMakeFiles/CMakeOutput.log
  - cat build_cblas/CMakeFiles/CMakeError.log
notifications:
  email:
    recipients:
      - eduard+btas@valeyev.net
    on_success: change
    on_failure: always
